//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VoiceRecorderEntities : DbContext
    {
        public VoiceRecorderEntities()
            : base("name=VoiceRecorderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_AGE_GROUP> TB_AGE_GROUP { get; set; }
        public DbSet<TB_AREA> TB_AREA { get; set; }
        public DbSet<TB_SCRIPT> TB_SCRIPT { get; set; }
        public DbSet<TB_SEX> TB_SEX { get; set; }
        public DbSet<TB_USER> TB_USER { get; set; }
        public DbSet<V_File> V_File { get; set; }
        public DbSet<TB_USER_SCRIPT> TB_USER_SCRIPT { get; set; }
        public DbSet<TB_FILE> TB_FILE { get; set; }
    }
}
