//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AGE_GROUP
    {
        public int ID { get; set; }
        public int AGE_GROUP_ID { get; set; }
        public string AGE_GROUP_DESCRIPTION { get; set; }
    }
}
