//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FILE
    {
        public int FILE_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_LOCATION { get; set; }
        public int SCRIPT_ID { get; set; }
        public int USER_ID { get; set; }
        public int AGE_GROUP_ID { get; set; }
        public int AREA_ID { get; set; }
        public int SEX_ID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> VOTE_GOOD { get; set; }
        public Nullable<int> VOTE_BAD { get; set; }
        public string SNR { get; set; }
    }
}
