//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_SCRIPT
    {
        public int ID { get; set; }
        public string USER_NAME { get; set; }
        public int SCRIPT_ID { get; set; }
        public Nullable<int> IS_READ { get; set; }
        public Nullable<int> STT { get; set; }
        public string SCRIPT_DESCRITPTION { get; set; }
        public Nullable<int> VOTE_GOOD { get; set; }
        public Nullable<int> VOTE_BAD { get; set; }
        public string SNR { get; set; }
    }
}
