//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_File
    {
        public int FILE_ID { get; set; }
        public string USER_NAME { get; set; }
        public string AGE_GROUP_DESCRIPTION { get; set; }
        public string AREA_DESCRIPTION { get; set; }
        public string SCRIPT_DESCRITPTION { get; set; }
        public Nullable<int> SCRIPT_ID { get; set; }
        public string SEX_DESCRIPTION { get; set; }
        public string FILE_LOCATION { get; set; }
        public string FILE_NAME { get; set; }
    }
}
